### ISSUE TITLE
Failed to move ADMX

### ISSUE THREAD

**Issue by CelsoSantos** [Fleex255/PolicyPlus#3] opened 2017-08-15 20:54 UTC
Hi,

I'm on Windows 10 Home but I'm having some trouble using this application on my machine.
First of all, it's probably worth mentioning that I'm on the Insiders Preview program and my current build is 16257
![screenshot_4](https://user-images.githubusercontent.com/1015506/29335957-42cf2676-8204-11e7-8669-d87d64e745be.png)

As soon as I start it I get the following popup with some error:

![screenshot_1](https://user-images.githubusercontent.com/1015506/29335833-d9ee1a9a-8203-11e7-8b65-b042a26d32f2.png)

Clicking OK will open the app (with blank screen) and then when I try to get the ADMX file it produces an error stating that it "Failed to move the ADMX".

![screenshot_2](https://user-images.githubusercontent.com/1015506/29335869-fbda105a-8203-11e7-913f-831477269832.png)
![screenshot_3](https://user-images.githubusercontent.com/1015506/29335870-fbe77d4e-8203-11e7-92fd-7ca835abe619.png)

What might be going on here?
Best Regards

**Comment by Fleex255** [comment] 2017-08-21 23:02
I am unable to reproduce the launching and download issues on Windows 10 Home x64 build 16257.1. Are you logged on as an administrator? If you are, Policy Plus asks to be elevated, but if not, it does its best to run anyway. The downloaded policy definitions cannot be installed without admin abilities. If that's not the problem, I will add some more logging so we can investigate more.

From your screenshots, it looks like there's something unusual going on with the message boxes - the error messages are cut off and the gray bottom bar doesn't contain the OK button. I can reproduce that issue with high DPI. To work around that for now, you can set "scaling performed by" to Application in the Compatibility tab, though this has the undesirable side effect of making a mess of some dialogs.

Thank you for the report!

**Comment by CelsoSantos** [comment] 2017-08-29 19:01
Hi @Fleex255 ,

I've gotten a new Windows Update meanwhile so today I tried to run PolicyPlus again both the Release Build and the Debug Build, both without success.

The new build number is this:
![image](https://user-images.githubusercontent.com/1015506/29838972-a7614ff6-8cf4-11e7-9438-c06536b14212.png)


As soon as I start the application (and taking into account your comments regarding the high DPI) I have a new screenshot to show:

![image](https://user-images.githubusercontent.com/1015506/29838918-83164688-8cf4-11e7-96e7-24b154135775.png)

The rest of the behaviour still remains: Fails to import the ADMX, shows nothing on screen. I think we'll need to do some more digging on this.

I've also changed from using my Microsoft Account to a Local Administrator account, still the same result.

**Comment by Fleex255** [comment] 2017-08-29 22:36
Thanks for following up! Could you please check whether the filename shown in that error message exists on your system? On a fresh copy of the previous build (16257 Home), it was already there for me. Either way, it is strange that Download ADMX Files is unable to copy the files it downloaded. I suspect an overzealous antivirus might be in play - you might try disabling your AV temporarily to see if that changes anything. I find Windows Defender very good; third party AV products have caused various problems for me in the past.

If antivirus isn't the problem, you might try downloading the ADMX files to a new folder in a non-system location and opening them from there. That might be a usable workaround until we figure out what's happening here.

**Comment by CelsoSantos** [comment] 2017-08-29 23:11
Hello again @Fleex255,

I seem to have solved the issue just now. I went ahead and started to inspect permissions and ownershipt of source/destination folders after taking a look at the code, particularly the DownloadAdmx.vb class and I had several issues with the PolicyDefinitions folders, especially with the en-US folder. So I started to change ownership and eventually copied the definitions manually there.

Now the UI does look as it should from the beginning.

Two things to notice still: If I attempt to download the files again, moving still fails. I have yet to try to change any Policies, will report back once I do.

**Comment by CelsoSantos** [comment] 2017-08-30 09:45
I haven't had time to debug, but meanwhile here's the shell output:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Celso Santos> Get-Acl C:\Windows\PolicyDefinitions | Format-List


Path   : Microsoft.PowerShell.Core\FileSystem::C:\Windows\PolicyDefinitions
Owner  : BUILTIN\Administradores
Group  : NT SERVICE\TrustedInstaller
Access : CREATOR OWNER Allow  268435456
         NT AUTHORITY\SYSTEM Allow  268435456
         NT AUTHORITY\SYSTEM Allow  Modify, Synchronize
         BUILTIN\Administradores Allow  268435456
         BUILTIN\Administradores Allow  FullControl
         BUILTIN\Utilizadores Allow  -1610612736
         BUILTIN\Utilizadores Allow  ReadAndExecute, Synchronize
         NT SERVICE\TrustedInstaller Allow  268435456
         NT SERVICE\TrustedInstaller Allow  FullControl
         AUTORIDADE DE PACOTE DE APLICAÇÃO\TODOS OS PACOTES DE APLICAÇÃO Allow  ReadAndExecute, Synchronize
         AUTORIDADE DE PACOTE DE APLICAÇÃO\TODOS OS PACOTES DE APLICAÇÃO Allow  -1610612736
         AUTORIDADE DE PACOTE DE APLICAÇÃO\TODOS OS PACOTES DE APLICAÇÕES COM RESTRIÇÃO Allow  ReadAndExecute,
         Synchronize
         AUTORIDADE DE PACOTE DE APLICAÇÃO\TODOS OS PACOTES DE APLICAÇÕES COM RESTRIÇÃO Allow  -1610612736
Audit  :
Sddl   : O:BAG:S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464D:PAI(A;OICIIO;GA;;;CO)(A;OICIIO;GA;;;S
         Y)(A;;0x1301bf;;;SY)(A;OICIIO;GA;;;BA)(A;;FA;;;BA)(A;OICIIO;GXGR;;;BU)(A;;0x1200a9;;;BU)(A;CIIO;GA;;;S-1-5-
         80-956008885-3418522649-1831038044-1853292631-2271478464)(A;;FA;;;S-1-5-80-956008885-3418522649-1831038044-
         1853292631-2271478464)(A;;0x1200a9;;;AC)(A;OICIIO;GXGR;;;AC)(A;;0x1200a9;;;S-1-15-2-2)(A;OICIIO;GXGR;;;S-1-
         15-2-2)
```

Weird thing, even though I've set my main language to be en-GB some stuff still shows in pt-PT, which is the language the PC came in. I've added en-GB after by using the settings on Windows. Don't know if that would make a difference

**Comment by Fleex255** [comment] 2017-08-30 14:36
Thank you for the language information! I believe we've found the problem. The MSI from Microsoft containing the new policy definitions only has ADML files for a handful of common language-region combinations, but [line 80](https://github.com/Fleex255/PolicyPlus/blob/79d4c87ca9ad639bda36de4a0f2c21a84248725b/PolicyPlus/DownloadAdmx.vb#L80) assumes there's an ADML subfolder for the current culture. If there's not, `moveFilesInDir` hits a `DirectoryNotFoundException` when calling `Directory.EnumerateFiles`.

Should be fixed in https://github.com/Fleex255/PolicyPlus/commit/8af01e8cfa161c878119f4a00b44ab34eb77daed - [debug build link](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) has been updated. Please try the Download ADMX Files feature again and let me know if we've got it working. 

Regarding the language inconsistency, it looks like [this guide](https://www.windowscentral.com/how-properly-change-system-default-language-windows-10) might be helpful for getting everything in the same language, though I have not personally tested it. You might also need to adjust the system locale (accessible from the dialog shown in step 13).

Thanks again!

**Comment by CelsoSantos** [comment] 2017-08-30 20:24
I can confirm that that debug build is working without presenting any of the before mentioned issues.
Acquiring the ADML files works without a problem.

Thank you.

**Closed** 2017-08-31 00:31 UTC
Labels: bug
