### ISSUE TITLE
"Failed to export REG!" error 

### ISSUE THREAD

**Issue by zdat** [Fleex255/PolicyPlus#50] opened 2021-07-28 15:52 UTC
I'm getting the error "Failed to export REG!" when trying to export the REG file for the computer (user works fine). Despite the error, a file is produced.

When I try to import that file on a new machine (virtual machine) I get another error; "An error occurred while trying to guess the prefix".

I'm just trying to backup all the changes I've made so I'm exporting everything. Not sure what the difference between .pol and .reg files is.

**Comment by Fleex255** [comment] 2021-07-28 16:11
Thank you for the report. Could you please double-check that you are using the newest version of Policy Plus (the June 2021 snapshot)? A similar bug that was present in the May 2020 snapshot [was fixed a few months ago](https://github.com/Fleex255/PolicyPlus/issues/37).

If there is still a problem, could you please share your `C:\Windows\System32\GroupPolicy\Machine\Registry.pol` file so I can see what kind of data is tripping up the REG exporter? You can make sure there is no sensitive data in the POL by looking at *File | Edit Raw POL* on the Computer source.

Regarding the difference between POL and REG, they are similar in that both specify changes to the Registry. POL files are used by Group Policy and are a bit more flexible in their ability to remove Registry entries, which is used when policies are set to Disabled. REG files are used by the standard Registry Editor, so they can be easily applied without Group Policy or Policy Plus.

**Comment by Fleex255** [comment] 2021-07-28 17:26
Actually, I can reproduce this error on the current version when there are values with very large integers. Investigating now.

**Comment by Fleex255** [comment] 2021-07-28 18:48
Integers large enough to have their sign bit set when interpreted as signed caused problems in some places. That, along with a crash when exporting a zero-length binary value, should be fixed in https://github.com/Fleex255/PolicyPlus/commit/5d4b5a433473d8e9e61381bdfc0e2ebb66f97093. At your convenience, please check if the [updated dev build](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) fixes the crash for you. (Note that Chrome currently refuses to keep the file due to an antivirus false positive. You may need to use Firefox or Edge for the download.)

**Closed** 2021-09-14 15:40 UTC
Labels: bug, likely resolved
