### ISSUE TITLE
does not reflect changes made in gpedit.msc

### ISSUE THREAD

**Issue by mailinglists35** [Fleex255/PolicyPlus#16] opened 2018-04-05 20:14 UTC
steps

- win10 home 64bit
- enable gpedit.msc via this script (gpedit-enabler.bat):
https://www.itechtics.com/?ddownload=26357
````@echo off 
pushd "%~dp0" 

dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientExtensions-Package~3*.mum >List.txt 
dir /b %SystemRoot%\servicing\Packages\Microsoft-Windows-GroupPolicy-ClientTools-Package~3*.mum >>List.txt 

for /f %%i in ('findstr /i . List.txt 2^>nul') do dism /online /norestart /add-package:"%SystemRoot%\servicing\Packages\%%i" 
pause
````

- go to comp - adm templates - win components - windows update - configure windows update - enable - 2 - apply

- go to policy plus

result:
not configured + 3

expected results:
enabled + 2

observations:
- it reflects changes only if i close it and reopen
- neither gpedit.msc detects changes made by policy plus

**Comment by Fleex255** [comment] 2018-04-11 16:48
Thanks for the detailed report!

This is the intended behavior. Policy Plus does not commit GPO changes to disk until you use *File | Save Policies*. Admittedly, that's not made very clear, since it doesn't prompt to save changes before closing. I should do something about that. Neither Policy Plus nor the LGPE scan for changes made since they opened; this would hinder performance and, in the case of Policy Plus, clobber any unsaved changes. I advise making Group Policy edits in only one program at once.

**Closed by Fleex255** 2018-04-11 16:48 UTC
