### ISSUE TITLE
"Policy definitions could not be loaded"

### ISSUE THREAD

**Issue by freMea** [Fleex255/PolicyPlus#1] opened 2017-07-15 18:09 UTC
App version | OS 
------------------ | ---- 
1.0.0.0 | Win 10 x64 pro (french) 14393 

## Steps to reproduce

1. Run **Policy Plus.exe**

## Results

Get this error (maybe related to my french OS)

![pp](https://user-images.githubusercontent.com/22337329/28241631-6fb538da-6998-11e7-9508-a98ef4db1219.PNG)

The french part means: _input string format is invalid_

Once I click OK, the GUI displays but no policies are loaded and I can't seem to manually load anything.

![ppg](https://user-images.githubusercontent.com/22337329/28241685-78d863b4-6999-11e7-9414-5a3e72d3d80e.PNG)

Hence I couldn't test your app on my PC.

**Comment by Fleex255** [comment] 2017-07-15 21:37
I am unable to reproduce this issue with the French policy definitions on an English Windows 10, so I will acquire a French version of Windows to test on. I'll keep you updated - thanks for the report!

**Comment by Fleex255** [comment] 2017-07-16 16:15
Reproduced on French Windows 10. Investigating now.

**Comment by Fleex255** [comment] 2017-07-16 19:36
Fixed in https://github.com/Fleex255/PolicyPlus/commit/79d4c87ca9ad639bda36de4a0f2c21a84248725b. The version field in ADMX/ADML files is a decimal value, with a period as the decimal separator. When running in a culture with the comma as the decimal separator, the one-argument overload of `Decimal.Parse` cannot handle values like that. The solution was to use the invariant culture for parsing that field. I also added a fallback to English ADML files if an ADMX corresponds to one that isn't found in the current language. The download link has been updated. Thanks again for your report!

**Closed by Fleex255** 2017-07-16 19:36 UTC
Labels: bug

**Comment by freMea** [comment] 2017-07-16 21:36
Nice job. I will be able to easily to backup/restore policies thanks to you. I would appreciate an option to increase font size though 😉

**Comment by Bricolas** [comment] 2019-01-09 12:54
Policy Plus
---------------------------
Policy definitions could not be loaded: Le fichier 'C:\WINDOWS\PolicyDefinitions\en-US\ShapeCollector.adml' est introuvable.
---------------------------
Version just downloaded from here : https://s3-us-west-2.amazonaws.com/policy-plus/Policy%20Plus.exe
Nevertheles, the program started.

Screenprints :
![policy plus error 20190109](https://user-images.githubusercontent.com/14942122/50900591-f479c300-1415-11e9-9793-2cb65d86b948.jpg)
![a propos de windows 20190109](https://user-images.githubusercontent.com/14942122/50900592-f479c300-1415-11e9-803a-85df542aa575.jpg)

**Comment by Fleex255** [comment] 2019-01-09 16:44
Thanks for the report! I suspect that the French version of Windows is missing the ShapeCollector.adml file. I just updated [the dev build link](https://s3-us-west-2.amazonaws.com/policy-plus/PolicyPlusDev.exe) with a version built for version 1809. Download that, then you can install the complete set of policy definitions using *Help | Acquire ADMX Files*. When possible, Policy Plus will use ADML files in your language, but if one is unavailable, Policy Plus will use the English version.
